name: Deploy to ECS on Development Push

on:
  push:
    branches:
      - master

env:
  ENVIRONMENT: ${{ vars.ENVIRONMENT || 'development' }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 리포지토리 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. 배포 정보 출력
      - name: Print deployment information
        run: |
          echo "=== 배포 정보 ==="
          echo "AWS Account ID: ${{ secrets.AWS_ACCOUNT_ID }}"
          echo "AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}"
          echo "AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          echo "AWS Region: ${{ secrets.AWS_REGION }}"
          echo "Environment: ${{ vars.ENVIRONMENT }}"
          echo "ECR Repository: ${{ secrets.ECR_REPOSITORY_NAME }}"
          echo "ECS Cluster: ${{ secrets.ECS_CLUSTER }}"
          echo "ECS Service: ${{ secrets.ECS_SERVICE }}"
          

      # 3. Java 환경 설정 (Spring Boot 프로젝트용)
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # 4. AWS CLI 설정 및 ECR 로그인
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # 5. Gradle 캐시 설정 (빌드 속도 개선)
      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-

      # 6. Docker 이미지 빌드
      - name: Build Docker image
        run: |
          IMAGE_TAG="${{ secrets.ECR_REPOSITORY_NAME }}:${{ vars.ENVIRONMENT }}"
          ./gradlew bootBuildImage --imageName=${IMAGE_TAG}

      # 7. ECR에 이미지 태그 지정 및 푸시
      - name: Tag and push image to Amazon ECR
        run: |
          ECR_URI="${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY_NAME }}"
          docker tag ${{ secrets.ECR_REPOSITORY_NAME }}:${{ vars.ENVIRONMENT }} ${ECR_URI}:${{ vars.ENVIRONMENT }}
          docker push ${ECR_URI}:${{ vars.ENVIRONMENT }}
          echo "Pushed image: ${ECR_URI}:${{ vars.ENVIRONMENT }}"

      # 8. ECS 태스크 정의 업데이트 및 배포
      - name: Update ECS service
        run: |
          ECR_URI="${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY_NAME }}"
          aws ecs update-service \
            --cluster ${{ secrets.ECS_CLUSTER }} \
            --service ${{ secrets.ECS_SERVICE }} \
            --force-new-deployment \
            --region ${{ secrets.AWS_REGION }}
          echo "ECS service ${{ secrets.ECS_SERVICE }} updated with new image: ${ECR_URI}:${{ vars.ENVIRONMENT }}"